#!/bin/sh
# $Id: buildconf,v 1.57 2002/07/21 13:09:06 sas Exp $

while test $# -gt 0; do
    if test "$1" = "--copy"; then
        automake_flags=--copy
    fi

    if test "$1" = "--ZendEngine2"; then
        ZENDDIR=ZendEngine2
        echo "Using Zend Engine 2 code"
    fi

    shift
done

if test -z "$ZENDDIR"; then
    ZENDDIR=Zend
    echo "using default Zend directory"
fi
 
rm -f generated_lists

${MAKE:-make} -s -f build/build.mk AMFLAGS="$automake_flags" ZENDDIR="$ZENDDIR"
