#!/bin/sh
#
# $Id: preconfig,v 1.1 1999/04/17 00:37:12 ssb Exp $

makefiles=`echo ext/*/Makefile.am | sed -e 's/\.am//g'`
rm -f configure.in
sed -e "s#@@EXT_MAKEFILES@@#$makefiles#" configure.in.in > configure.in
